Weblink
prabhm512/project-2 pull request #79
Opened 2020-11-26 12:25 UTC by felipesqf

2020-11-26 12:27 UTC, felipesqf reviewed
THe is the coding change to add the modal Thanks message upon submiting the from.

2020-11-26 12:27 UTC, felipesqf commented on public/css/style.css
> -    }
corrected in the last commit

2020-11-26 15:38 UTC, prabhm512 requested changes
Git pull in main then git merge main in feature need to be run. I don't think this commit has the changes made for the landing page.

2020-11-28 02:02 UTC, prabhm512 approved these changes

2020-11-28 02:02 UTC, merged